title: Sharad Katre
description: Full Stack Developer | MERN | Next.js | FastAPI | AI
url: ""
baseurl: ""

markdown: kramdown
theme: null

author:
  name: Sharad Katre
  email: sharadkatre01@gmail.com

social:
  github: sharadkatre
  linkedin: sharad-katre
  email: sharadkatre01@gmail.com

plugins:
  - jekyll-seo-tag
